# Generated by Django 2.2.28 on 2022-05-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sunlight', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('preparation_time', models.IntegerField()),
                ('difficulty', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('notes', models.CharField(max_length=1500)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magdziungla.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ManyToManyField(to='magdziungla.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('plant', models.ManyToManyField(to='magdziungla.Plant')),
                ('pot', models.ManyToManyField(to='magdziungla.Pot')),
                ('soil', models.ManyToManyField(to='magdziungla.Soil')),
            ],
        ),
    ]
