# Generated by Django 2.2.28 on 2022-05-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0002_remove_plant_preparation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sunlight',
            field=models.CharField(max_length=20),
        ),
    ]
