# Generated by Django 2.2.28 on 2022-05-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0003_auto_20220529_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sunlight',
            field=models.CharField(max_length=64),
        ),
    ]
