# Generated by Django 2.2.28 on 2022-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0004_auto_20220529_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
    ]
