# Generated by Django 2.2.28 on 2022-05-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0005_auto_20220529_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='updated',
            field=models.CharField(max_length=120),
        ),
    ]
