# Generated by Django 2.2.28 on 2022-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0006_auto_20220529_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='updated',
            field=models.DateTimeField(blank=True),
        ),
    ]
