# Generated by Django 2.2.28 on 2022-05-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0007_auto_20220529_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
