# Generated by Django 2.2.28 on 2022-05-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0008_plant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='soil',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
