# Generated by Django 2.2.28 on 2022-05-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0009_auto_20220529_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='radius',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
