# Generated by Django 2.2.28 on 2022-05-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0011_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='type',
        ),
        migrations.AddField(
            model_name='soil',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
