# Generated by Django 2.2.28 on 2022-06-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0013_auto_20220530_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='plant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magdziungla.Plant'),
        ),
        migrations.AddField(
            model_name='soil',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='soil',
            name='type',
        ),
        migrations.AddField(
            model_name='soil',
            name='type',
            field=models.ManyToManyField(to='magdziungla.Plant'),
        ),
    ]
