# Generated by Django 2.2.28 on 2022-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magdziungla', '0015_auto_20220605_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
